/**
 * SVG Normalizer — Cleans up raw SVG from Claude.
 *
 * Intercepts the SVG code generated by Claude and normalizes it:
 * - Forces stroke width to base value (2px default)
 * - Aligns all nodes to pixel grid (snapping)
 * - Removes junk code (empty groups, redundant metadata, unnecessary transforms)
 * - Standardizes viewBox
 *
 * Output: A clean, "native" vector ready for the Transformer.
 */

import type { SvgDocument, SvgElement, NormalizationResult, NormalizationChange } from './types.js';

export interface NormalizerOptions {
  /** Base stroke width to enforce (default: 2) */
  baseStrokeWidth?: number;
  /** Target grid size for pixel snapping (default: 24) */
  gridSize?: number;
  /** Whether to snap coordinates to integers (default: true) */
  pixelSnap?: boolean;
}

const DEFAULT_OPTIONS: Required<NormalizerOptions> = {
  baseStrokeWidth: 2,
  gridSize: 24,
  pixelSnap: true,
};

/**
 * Normalize an SvgDocument: clean, snap, and standardize.
 */
export function normalizeSvg(
  doc: SvgDocument,
  options: NormalizerOptions = {},
): NormalizationResult {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const changes: NormalizationChange[] = [];

  let result = { ...doc, elements: [...doc.elements] };

  // 1. Standardize viewBox
  result = standardizeViewBox(result, opts.gridSize, changes);

  // 2. Remove junk (empty groups, transforms)
  result = removeJunk(result, changes);

  // 3. Force stroke width
  result = forceStrokeWidth(result, opts.baseStrokeWidth, changes);

  // 4. Pixel snap coordinates
  if (opts.pixelSnap) {
    result = snapToPixelGrid(result, changes);
  }

  return { document: result, changes };
}

/**
 * Standardize viewBox to target grid size.
 */
function standardizeViewBox(
  doc: SvgDocument,
  gridSize: number,
  changes: NormalizationChange[],
): SvgDocument {
  if (doc.viewBox.width !== gridSize || doc.viewBox.height !== gridSize) {
    changes.push({
      type: 'viewbox-standardized',
      description: `ViewBox changed from ${doc.viewBox.width}×${doc.viewBox.height} to ${gridSize}×${gridSize}`,
    });
  }

  // Scale elements if viewBox differs from target
  const scaleX = gridSize / doc.viewBox.width;
  const scaleY = gridSize / doc.viewBox.height;

  let elements = doc.elements;
  if (scaleX !== 1 || scaleY !== 1) {
    elements = doc.elements.map((el) => scaleElement(el, scaleX, scaleY));
  }

  return {
    ...doc,
    viewBox: { x: 0, y: 0, width: gridSize, height: gridSize },
    width: gridSize,
    height: gridSize,
    elements,
  };
}

/**
 * Remove junk: empty groups, unnecessary transforms, metadata.
 */
function removeJunk(doc: SvgDocument, changes: NormalizationChange[]): SvgDocument {
  const cleanedElements = cleanElements(doc.elements);
  const removed = countElements(doc.elements) - countElements(cleanedElements);

  if (removed > 0) {
    changes.push({
      type: 'junk-removed',
      description: `Removed ${removed} junk element(s) (empty groups, redundant nodes)`,
    });
  }

  return { ...doc, elements: cleanedElements };
}

/**
 * Recursively clean elements: remove empty groups, flatten single-child groups.
 */
function cleanElements(elements: SvgElement[]): SvgElement[] {
  const result: SvgElement[] = [];

  for (const el of elements) {
    if (el.type === 'group') {
      const cleanedChildren = cleanElements(el.children);

      // Skip empty groups
      if (cleanedChildren.length === 0) continue;

      // Flatten single-child groups with no significant attributes
      if (cleanedChildren.length === 1 && !hasSignificantAttributes(el.attributes)) {
        result.push(cleanedChildren[0]!);
        continue;
      }

      result.push({ ...el, children: cleanedChildren });
    } else {
      // Keep paths that have commands
      if (el.commands.length > 0) {
        result.push(el);
      }
    }
  }

  return result;
}

/**
 * Force all stroke widths to the base value.
 */
function forceStrokeWidth(
  doc: SvgDocument,
  baseStrokeWidth: number,
  changes: NormalizationChange[],
): SvgDocument {
  let changed = false;

  const elements = doc.elements.map((el) => {
    const result = forceElementStroke(el, baseStrokeWidth);
    if (result.changed) changed = true;
    return result.element;
  });

  if (changed) {
    changes.push({
      type: 'stroke-forced',
      description: `All stroke widths normalized to ${baseStrokeWidth}px`,
    });
  }

  return { ...doc, elements };
}

function forceElementStroke(
  el: SvgElement,
  strokeWidth: number,
): { element: SvgElement; changed: boolean } {
  if (el.type === 'path') {
    const hasStroke = el.attributes.stroke && el.attributes.stroke !== 'none';
    if (hasStroke && el.attributes.strokeWidth !== strokeWidth) {
      return {
        element: {
          ...el,
          attributes: { ...el.attributes, strokeWidth },
        },
        changed: true,
      };
    }
    return { element: el, changed: false };
  }

  // Group
  let groupChanged = false;
  const children = el.children.map((child) => {
    const result = forceElementStroke(child, strokeWidth);
    if (result.changed) groupChanged = true;
    return result.element;
  });

  return { element: { ...el, children }, changed: groupChanged };
}

/**
 * Snap all coordinates to the pixel grid (round to nearest integer).
 */
function snapToPixelGrid(
  doc: SvgDocument,
  changes: NormalizationChange[],
): SvgDocument {
  let snapped = false;

  const elements = doc.elements.map((el) => {
    const result = snapElement(el);
    if (result.changed) snapped = true;
    return result.element;
  });

  if (snapped) {
    changes.push({
      type: 'grid-snapped',
      description: 'All coordinates snapped to pixel grid (integer values)',
    });
  }

  return { ...doc, elements };
}

function snapElement(el: SvgElement): { element: SvgElement; changed: boolean } {
  if (el.type === 'path') {
    let pathChanged = false;
    const commands = el.commands.map((cmd) => {
      const snappedValues = cmd.values.map((v) => {
        const rounded = Math.round(v);
        if (rounded !== v) pathChanged = true;
        return rounded;
      });
      return { ...cmd, values: snappedValues };
    });

    return {
      element: { ...el, commands },
      changed: pathChanged,
    };
  }

  // Group
  let groupChanged = false;
  const children = el.children.map((child) => {
    const result = snapElement(child);
    if (result.changed) groupChanged = true;
    return result.element;
  });

  return { element: { ...el, children }, changed: groupChanged };
}

// ─── Helpers ───────────────────────────────────────────────────

function scaleElement(el: SvgElement, scaleX: number, scaleY: number): SvgElement {
  if (el.type === 'path') {
    const commands = scalePathCommands(el.commands, scaleX, scaleY);
    return { ...el, commands };
  }

  return {
    ...el,
    children: el.children.map((child) => scaleElement(child, scaleX, scaleY)),
  };
}

function scalePathCommands(
  commands: import('./types.js').PathCommand[],
  scaleX: number,
  scaleY: number,
): import('./types.js').PathCommand[] {
  return commands.map((cmd) => {
    const type = cmd.type.toUpperCase();

    if (type === 'Z') return cmd;
    if (type === 'H') return { ...cmd, values: cmd.values.map((v) => v * scaleX) };
    if (type === 'V') return { ...cmd, values: cmd.values.map((v) => v * scaleY) };

    // For most commands, alternate x,y values
    const values = cmd.values.map((v, i) => v * (i % 2 === 0 ? scaleX : scaleY));
    return { ...cmd, values };
  });
}

function countElements(elements: SvgElement[]): number {
  let count = 0;
  for (const el of elements) {
    count++;
    if (el.type === 'group') {
      count += countElements(el.children);
    }
  }
  return count;
}

function hasSignificantAttributes(attrs: import('./types.js').SvgAttributes): boolean {
  return !!(attrs.fill || attrs.stroke || attrs.opacity !== undefined || attrs.transform);
}
