/**
 * Font Generator — Generates TTF/WOFF2 icon fonts.
 * PRD §4B: "Icon Font (TTF/WOFF2): Con ligaduras inteligentes."
 *
 * This module defines the interface. Full font binary generation
 * will integrate opentype.js in a future iteration.
 */

import type { SvgDocument } from '../engine/types.js';
import { exportSvg } from './svg-exporter.js';

export interface FontGlyph {
  name: string;
  unicode: string;
  svg: string;
  ligature?: string;
}

export interface FontConfig {
  fontFamily: string;
  glyphs: FontGlyph[];
}

export interface FontOutput {
  config: FontConfig;
  /** SVG font source (intermediate format) */
  svgFontSource: string;
  /** Placeholder for binary font data — will be generated by opentype.js */
  ttfAvailable: boolean;
  woff2Available: boolean;
}

/**
 * Prepare a font configuration from icon documents.
 */
export function prepareFontConfig(
  icons: Array<{ name: string; doc: SvgDocument }>,
  fontFamily = 'IconCraftIcons',
): FontConfig {
  const startCodepoint = 0xE000; // Private Use Area

  const glyphs: FontGlyph[] = icons.map((icon, i) => ({
    name: icon.name,
    unicode: String.fromCodePoint(startCodepoint + i),
    svg: exportSvg(icon.doc, { minify: true }),
    ligature: icon.name.replace(/[-_]/g, ''),
  }));

  return { fontFamily, glyphs };
}

/**
 * Generate font output (SVG font source + availability flags).
 * Binary TTF/WOFF2 generation requires opentype.js integration.
 */
export function generateFont(config: FontConfig): FontOutput {
  const glyphEntries = config.glyphs
    .map(
      (g) =>
        `    <glyph glyph-name="${g.name}" unicode="${g.unicode}" d=""/>`,
    )
    .join('\n');

  const svgFontSource = `<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <defs>
    <font id="${config.fontFamily}">
      <font-face font-family="${config.fontFamily}" units-per-em="1024"/>
      <missing-glyph d=""/>
${glyphEntries}
    </font>
  </defs>
</svg>`;

  return {
    config,
    svgFontSource,
    ttfAvailable: false,
    woff2Available: false,
  };
}
