/**
 * Angular Emitter — Generates an Angular icon component.
 */

import type { SvgDocument } from '../../engine/types.js';
import { serializeSvg } from '../../engine/svg-parser.js';

export interface AngularEmitterOptions {
  componentName: string;
  selector?: string;
}

export function emitAngular(doc: SvgDocument, options: AngularEmitterOptions): string {
  const { componentName } = options;
  const selector = options.selector ?? `app-icon-${toKebab(componentName)}`;
  const svgString = serializeSvg(doc);

  return `import { Component, Input } from '@angular/core';

@Component({
  selector: '${selector}',
  standalone: true,
  template: \`
    ${svgString.replace(/"/g, "'")}
  \`,
  styles: [\`
    :host { display: inline-flex; }
    svg { width: 100%; height: 100%; }
  \`]
})
export class ${componentName}Component {
  @Input() size = ${doc.viewBox.width};
  @Input() color = 'currentColor';
}
// Generated by IconCraft AI
`;
}

function toKebab(name: string): string {
  return name.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}
