/**
 * Compose Emitter — Generates a Jetpack Compose icon composable.
 * PRD §4B: "Mobile: Jetpack Compose (Android)"
 */

import type { SvgDocument } from '../../engine/types.js';
import { serializePathData } from '../../engine/svg-parser.js';

export interface ComposeEmitterOptions {
  functionName: string;
  packageName?: string;
}

export function emitCompose(doc: SvgDocument, options: ComposeEmitterOptions): string {
  const { functionName, packageName = 'com.iconcraft.icons' } = options;
  const w = doc.viewBox.width;


  const pathStatements = doc.elements
    .filter((el): el is Extract<typeof el, { type: 'path' }> => el.type === 'path')
    .map((path) => {
      const d = serializePathData(path.commands);
      const sw = path.attributes.strokeWidth ?? 2;
      return `        drawPath(
            path = PathParser.createPathFromPathData("${d}")!!.asComposePath(),
            color = tint,
            style = Stroke(width = ${sw}.dp.toPx())
        )`;
    })
    .join('\n');

  return `package ${packageName}

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.size
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.unit.dp
import androidx.core.graphics.PathParser

@Composable
fun ${functionName}(
    modifier: Modifier = Modifier,
    tint: Color = Color.Black,
    size: Int = ${w}
) {
    Canvas(modifier = modifier.size(size.dp)) {
${pathStatements}
    }
}
// Generated by IconCraft AI
`;
}
