/**
 * CSS Sprite Emitter — Generates a CSS class with SVG background.
 * PRD §4B: "Desktop: CSS Sprite"
 */

import type { SvgDocument } from '../../engine/types.js';
import { exportSvgDataUri } from '../svg-exporter.js';

export interface CssSpriteEmitterOptions {
  className: string;
}

export function emitCssSprite(doc: SvgDocument, options: CssSpriteEmitterOptions): string {
  const { className } = options;
  const dataUri = exportSvgDataUri(doc);
  const w = doc.viewBox.width;
  const h = doc.viewBox.height;

  return `.${className} {
  display: inline-block;
  width: ${w}px;
  height: ${h}px;
  background-image: url("${dataUri}");
  background-repeat: no-repeat;
  background-size: contain;
}
/* Generated by IconCraft AI */
`;
}
