/**
 * Swift Emitter — Generates a SwiftUI icon view.
 * PRD §4B: "Mobile: Swift (iOS)"
 */

import type { SvgDocument } from '../../engine/types.js';
import { serializePathData } from '../../engine/svg-parser.js';

export interface SwiftEmitterOptions {
  structName: string;
}

export function emitSwift(doc: SvgDocument, options: SwiftEmitterOptions): string {
  const { structName } = options;
  const w = doc.viewBox.width;


  const pathStatements = doc.elements
    .filter((el): el is Extract<typeof el, { type: 'path' }> => el.type === 'path')
    .map((path, i) => {
      const d = serializePathData(path.commands);
      const strokeW = path.attributes.strokeWidth ?? 2;
      return `            // Path ${i + 1}
            Path(svgPath: "${d}")
                .stroke(color, lineWidth: ${strokeW})`;
    })
    .join('\n');

  return `import SwiftUI

struct ${structName}: View {
    var size: CGFloat = ${w}
    var color: Color = .primary

    var body: some View {
        Canvas { context, canvasSize in
            let scale = min(canvasSize.width, canvasSize.height) / ${w}
            context.scaleBy(x: scale, y: scale)
${pathStatements}
        }
        .frame(width: size, height: size)
    }
}

#Preview {
    ${structName}()
}
// Generated by IconCraft AI
`;
}
