/**
 * Vue Emitter — Generates a Vue SFC icon component.
 */

import type { SvgDocument } from '../../engine/types.js';
import { serializeSvg } from '../../engine/svg-parser.js';

export interface VueEmitterOptions {
  componentName: string;
}

export function emitVue(doc: SvgDocument, options: VueEmitterOptions): string {
  const svgString = serializeSvg(doc);

  return `<script setup lang="ts">
defineProps<{
  size?: number;
  color?: string;
}>();
</script>

<template>
  ${svgString}
</template>

<style scoped>
svg {
  width: v-bind(size ? size + 'px' : '${doc.viewBox.width}px');
  height: v-bind(size ? size + 'px' : '${doc.viewBox.height}px');
  color: v-bind(color || 'currentColor');
}
</style>
<!-- ${options.componentName} — Generated by IconCraft AI -->
`;
}
