/**
 * XAML Emitter — Generates a XAML resource for WPF/UWP.
 * PRD §4B: "Desktop: XAML"
 */

import type { SvgDocument } from '../../engine/types.js';
import { serializePathData } from '../../engine/svg-parser.js';

export interface XamlEmitterOptions {
  resourceKey: string;
}

export function emitXaml(doc: SvgDocument, options: XamlEmitterOptions): string {
  const { resourceKey } = options;
  const w = doc.viewBox.width;
  const h = doc.viewBox.height;

  const pathElements = doc.elements
    .filter((el): el is Extract<typeof el, { type: 'path' }> => el.type === 'path')
    .map((path) => {
      const d = serializePathData(path.commands);
      const sw = path.attributes.strokeWidth ?? 2;
      return `      <Path Data="${d}" Stroke="{Binding Foreground, RelativeSource={RelativeSource AncestorType=ContentControl}}" StrokeThickness="${sw}"/>`;
    })
    .join('\n');

  return `<!-- ${resourceKey} — Generated by IconCraft AI -->
<Viewbox x:Key="${resourceKey}" Width="${w}" Height="${h}">
  <Canvas Width="${w}" Height="${h}">
${pathElements}
  </Canvas>
</Viewbox>
`;
}
